import weddingImg from '@/assets/landing/categories/wedding.jpg';
import fashionImg from '@/assets/landing/categories/fashion.jpg';
import portraitImg from '@/assets/landing/categories/portrait.jpg';
import birthdayImg from '@/assets/landing/categories/birthday.jpg';
import travelImg from '@/assets/landing/categories/travel.jpg';
import corporateImg from '@/assets/landing/categories/corporate.jpg';
import avatar1 from '@/assets/landing/avatar-1.jpg';
import avatar2 from '@/assets/landing/avatar-2.jpg';
import avatar3 from '@/assets/landing/avatar-3.jpg';
import avatar4 from '@/assets/landing/avatar-4.jpg';
import creator1 from '@/assets/landing/featured-creator-1.jpg';
import creator2 from '@/assets/landing/featured-creator-2.jpg';
import type { EventTimelineDay } from '../types';

/** Demo day anchored so "live" slot can be computed relative to "now" in the service */
const DAY = '2024-05-24';

export const DEMO_EVENT_TIMELINE: EventTimelineDay = {
  id: 'evt-rohan-priya-2024',
  coupleLine: 'Rohan & Priya',
  eventName: 'The Wedding Celebration',
  eventDate: '24 May 2024',
  eventDateISO: `${DAY}T00:00:00`,
  location: 'Jaipur, Rajasthan',
  coverImage: weddingImg,
  progressPercent: 72,
  totalCoverageLabel: '2.3K',
  clientSatisfaction: 98,
  hoursCoverage: 16,
  team: [
    {
      id: 't1',
      name: 'Aria Moore',
      role: 'lead',
      roleLabel: 'Lead Photographer',
      avatar: creator1,
      phone: '+91 98765 43210',
    },
    {
      id: 't2',
      name: 'Kabir Rao',
      role: 'videographer',
      roleLabel: 'Lead Videographer',
      avatar: creator2,
      phone: '+91 98765 43211',
    },
    {
      id: 't3',
      name: 'Noor Fatima',
      role: 'drone',
      roleLabel: 'Drone Operator',
      avatar: avatar3,
      phone: '+91 98765 43212',
    },
    {
      id: 't4',
      name: 'Ishaan Verma',
      role: 'photographer',
      roleLabel: 'Second Shooter',
      avatar: avatar4,
    },
    {
      id: 't5',
      name: 'Meera Shah',
      role: 'assistant',
      roleLabel: 'Assistant',
      avatar: avatar1,
    },
  ],
  slots: [
    {
      id: 's1',
      title: 'Bride Makeup',
      description: 'Getting ready coverage — bridal glam & candid moments.',
      icon: 'sparkles',
      startTime: `${DAY}T08:00:00`,
      endTime: `${DAY}T09:30:00`,
      venue: 'Bridal Suite · Fairmont Jaipur',
      status: 'completed',
      notes: 'Natural window light preferred.',
      photoCount: 120,
      videoCount: 8,
      teamIds: ['t1', 't5'],
      gallerySlug: 'rohit-priya-wedding',
      thumbnail: fashionImg,
      progressPercent: 100,
    },
    {
      id: 's2',
      title: 'Bride Portrait Session',
      description: 'Soft portraits before the festivities begin.',
      icon: 'camera',
      startTime: `${DAY}T09:30:00`,
      endTime: `${DAY}T10:00:00`,
      venue: 'Palace Gardens',
      status: 'completed',
      photoCount: 64,
      videoCount: 3,
      teamIds: ['t1', 't4'],
      gallerySlug: 'rohit-priya-wedding',
      thumbnail: portraitImg,
      progressPercent: 100,
    },
    {
      id: 's3',
      title: 'Haldi Ceremony',
      description: 'Vibrant turmeric ritual with family & friends.',
      icon: 'sun',
      startTime: `${DAY}T10:00:00`,
      endTime: `${DAY}T11:30:00`,
      venue: 'Courtyard Lawn',
      status: 'completed',
      photoCount: 186,
      videoCount: 12,
      teamIds: ['t1', 't2', 't4'],
      gallerySlug: 'rohit-priya-wedding',
      thumbnail: birthdayImg,
      progressPercent: 100,
    },
    {
      id: 's4',
      title: 'Family Photos',
      description: 'Group portraits and generation frames.',
      icon: 'users',
      startTime: `${DAY}T11:30:00`,
      endTime: `${DAY}T13:00:00`,
      venue: 'Heritage Courtyard',
      status: 'completed',
      photoCount: 98,
      videoCount: 4,
      teamIds: ['t1', 't4'],
      thumbnail: corporateImg,
      progressPercent: 100,
    },
    {
      id: 's5',
      title: 'Lunch Break',
      description: 'Team recharge & gear check.',
      icon: 'utensils',
      startTime: `${DAY}T13:00:00`,
      endTime: `${DAY}T15:00:00`,
      venue: 'Staff Dining',
      status: 'completed',
      photoCount: 12,
      videoCount: 0,
      teamIds: ['t1', 't2', 't3', 't4', 't5'],
      thumbnail: travelImg,
      progressPercent: 100,
    },
    {
      id: 's6',
      title: 'Mehendi Ceremony',
      description: 'Intricate henna art and joyful conversations.',
      icon: 'hand',
      startTime: `${DAY}T15:00:00`,
      endTime: `${DAY}T17:00:00`,
      venue: 'Mehendi Pavilion',
      status: 'live',
      notes: 'Focus on hands detail + candid laughter.',
      photoCount: 142,
      videoCount: 9,
      teamIds: ['t1', 't2', 't5'],
      gallerySlug: 'rohit-priya-wedding',
      thumbnail: fashionImg,
      progressPercent: 58,
    },
    {
      id: 's7',
      title: 'Sangeet',
      description: 'Dance performances and musical celebration.',
      icon: 'music',
      startTime: `${DAY}T17:00:00`,
      endTime: `${DAY}T18:30:00`,
      venue: 'Grand Ballroom',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't2', 't3', 't4'],
      thumbnail: weddingImg,
    },
    {
      id: 's8',
      title: 'Baraat',
      description: 'Groom procession with dhol & energy.',
      icon: 'party',
      startTime: `${DAY}T18:30:00`,
      endTime: `${DAY}T19:00:00`,
      venue: 'Main Entrance Gate',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't2', 't3'],
      thumbnail: travelImg,
    },
    {
      id: 's9',
      title: 'Wedding Ceremony',
      description: 'Sacred vows under the floral mandap.',
      icon: 'heart',
      startTime: `${DAY}T19:00:00`,
      endTime: `${DAY}T20:30:00`,
      venue: 'Mandap Hall',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't2', 't3', 't4'],
      gallerySlug: 'rohit-priya-wedding',
      thumbnail: weddingImg,
    },
    {
      id: 's10',
      title: 'Varmala',
      description: 'Garland exchange — two hearts becoming one.',
      icon: 'flower',
      startTime: `${DAY}T20:30:00`,
      endTime: `${DAY}T21:00:00`,
      venue: 'Mandap Hall',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't2'],
      thumbnail: portraitImg,
    },
    {
      id: 's11',
      title: 'Pheras',
      description: 'Seven circles, seven promises.',
      icon: 'circle',
      startTime: `${DAY}T21:00:00`,
      endTime: `${DAY}T22:30:00`,
      venue: 'Mandap Hall',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't2', 't4'],
      thumbnail: birthdayImg,
    },
    {
      id: 's12',
      title: 'Reception',
      description: 'Toasts, twirls, and endless smiles.',
      icon: 'party',
      startTime: `${DAY}T22:30:00`,
      endTime: `${DAY}T23:30:00`,
      venue: 'Reception Lawn',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't2', 't3', 't4', 't5'],
      thumbnail: corporateImg,
    },
    {
      id: 's13',
      title: 'Couple Portrait',
      description: 'Just the two of them — framed in night light.',
      icon: 'camera',
      startTime: `${DAY}T23:30:00`,
      endTime: '2024-05-25T00:30:00',
      venue: 'Palace Terrace',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't2'],
      thumbnail: portraitImg,
    },
    {
      id: 's14',
      title: 'Event Completed',
      description: 'Wrap, backups, and client thank-you.',
      icon: 'check',
      startTime: '2024-05-25T00:30:00',
      endTime: '2024-05-25T01:00:00',
      venue: 'Production Desk',
      status: 'upcoming',
      photoCount: 0,
      videoCount: 0,
      teamIds: ['t1', 't5'],
      thumbnail: avatar2,
    },
  ],
};
